### ISSUE TITLE
Can't compile for iOS physical devices

### ISSUE THREAD

**Issue by bigBoy-mm** [UserEngage/Flutter-SDK#1]
We've added sdk plugin to our project:

`flutter_user_sdk: ^0.0.1`

After that we can not compile our app on iOS **physical** devices. There is some issue with on of dependency:

```
Could not build the precompiled application for the device.
Error (Xcode): '/Users/marcinmakurat/furgonetka/application-flutter/build/ios/Debug-iphoneos/awesome_notifications/awesome_notifications.framework/awesome_notifications(awesome_notifications-dummy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/marcinmakurat/furgonetka/application-flutter/build/ios/Debug-iphoneos/awesome_notifications/awesome_notifications.framework/awesome_notifications' for architecture arm64
```

We didn't notice the above problem on iOS simulators and android devices (also physical). We use Fluter 2.10.5.

**Comment by marcszczygiel** [comment]
Hey @bigBoy-mm,

Thank you for your report. We're analyzing your issue. The update should be released soon.
I will keep you updated

**Comment by HmmOfRivia** [comment]
Hi,
Flutter introduced version 3.0.0 and some packages adjusted API. 
That probably caused problem mentioned above. 

Please import this ref if You use Flutter 2.0.0-2.10.5
  flutter_user_sdk:
   git:
    url: https://github.com/UserEngage/Flutter-SDK.git
    ref: c4d301576ad1759e777244d573705a753d9c47fe

Also check our docs to properly integrate package:
https://user.com/en/mobile-sdk/installation-flutter/

You also can try to clean build folder with 'flutter clean' before running project.
