### ISSUE TITLE
Unexpectedly crashes on iOS simulators with M1

### ISSUE THREAD

**Issue by bigBoy-mm** [UserEngage/Flutter-SDK#2]
There is some issue with "UserComSDK.instance.initialize" method on M1 machine. Our app unexpectedly crashes after calling the mentioned mathod. The problem is on iOS simulators with M1 machine. Everything is ok with Intel.

**Comment by marcszczygiel** [comment]
Hey @bigBoy-mm,

Thank you for your report. We're analyzing your issue. The update should be released soon.
I will keep you updated

**Comment by HmmOfRivia** [comment]
Hi. 
We analyzed problem with initializing our SDK. Package uses some dependencies which requires additional setup (Firebase).
When You run project on IOS without GoogleService.info imported into project, app may crash.
We prepared detailed documentation how to integrate SDK. Follow them to resolve your problem.

Please check our docs: https://user.com/en/mobile-sdk/installation-flutter/
