### ISSUE TITLE
App crashes on iOS when receive push notifications

### ISSUE THREAD

**Issue by bigBoy-mm** [UserEngage/Flutter-SDK#3]
We've tested your plugin on iOS 15.x and noticed problem with push notifications. The app just crashes when receive them. Snippet of log attached below:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16ef63fb0)
    frame #0: 0x0000000192620f48 libsystem_malloc.dylib`nanov2_allocate_from_block + 8
libsystem_malloc.dylib`nanov2_allocate_from_block:
->  0x192620f48 <+8>:  stp    x28, x27, [sp, #0x20]
    0x192620f4c <+12>: stp    x26, x25, [sp, #0x30]
    0x192620f50 <+16>: stp    x24, x23, [sp, #0x40]
    0x192620f54 <+20>: stp    x22, x21, [sp, #0x50]
Target 0: (Runner) stopped.
Lost connection to device.
```

We did some research about the issue and looks that "awesome_notifications" cause the problem and even the community reported the same issue. You can check more info here: [[firebase_messaging] EXC_BAD_ACCESS](https://github.com/firebase/flutterfire/issues/8065)

We also performed independent tests with the "awesome_notifications"  and looks that the newest version [0.7.0-beta.5](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.5) work well.

**Comment by marcszczygiel** [comment]
Hey @bigBoy-mm,

We're analyzing your issue. I'll keep you updated.

Best,
Marcin

**Comment by marcszczygiel** [comment]
It's resolved now. 

Best,
Marcin
